include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-jluNetworkLogin
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=jluNetworkLogin
LUCI_DEPENDS:=+jluNetworkLogin
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

$(eval $(call BuildPackage,luci-app-jluNetworkLogin))
